#!/usr/bin/env bash
# Puts the claude-account CLI on PATH and adds the claude-as shell helper + completion.
# Works from a Claude Code plugin install (path resolved live from the plugin registry
# on every call) or from a plain clone (falls back to this checkout).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$HERE/.." && pwd)"
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
SHIM="$BIN_DIR/claude-account"
MARK_BEGIN="# >>> claude-account >>>"
MARK_END="# <<< claude-account <<<"

if [ -z "${RC:-}" ]; then
  case "${SHELL:-}" in
    */bash) RC="$HOME/.bashrc" ;;
    *)      RC="$HOME/.zshrc" ;;
  esac
fi

for dep in jq claude; do
  command -v "$dep" >/dev/null 2>&1 || { echo "install.sh: missing dependency: $dep" >&2; exit 1; }
done
if [ "$(uname -s)" = Darwin ]; then
  command -v security >/dev/null 2>&1 || { echo "install.sh: missing dependency: security (macOS Keychain CLI)" >&2; exit 1; }
fi

# The rc block defines claude-as and _claude_as_names; a second definition outside the block would
# shadow ours or be shadowed by it, so stop before touching anything.
# Only the begin marker closest before the end marker opens the block: an earlier begin whose block lost its
# end (a truncated write, user lines appended after it) is outside, as are the lines that follow it.
if [ -f "$RC" ]; then
  conflicts=$(awk -v b="$MARK_BEGIN" -v e="$MARK_END" '
    function hit(t) {
      return t !~ /^#/ && (t ~ /^alias[ \t].*(^|[ \t])(claude-as|_claude_as_names)=/ ||
        t ~ /^function[ \t]+(claude-as|_claude_as_names)([ \t(]|$)/ || t ~ /^(claude-as|_claude_as_names)[ \t]*\(\)/)
    }
    { t=$0; sub(/^[ \t]+/, "", t); sub(/[ \t]+$/, "", t) }
    t==b { printf "%s", buf; buf=""; inb=1; next }
    t==e && inb && !done { buf=""; inb=0; done=1; next }
    hit(t) { line=sprintf("  line %d: %s\n", NR, t); if (inb && !done) buf=buf line; else printf "%s", line }
    END { printf "%s", buf }
  ' "$RC")
  if [ -n "$conflicts" ]; then
    echo "install.sh: $RC already defines a name claude-as uses (claude-as, _claude_as_names). Remove or rename it, then rerun:" >&2
    echo "$conflicts" >&2
    exit 1
  fi
fi

chmod +x "$HERE/claude-account.sh"
mkdir -p "$BIN_DIR"
rm -f "$SHIM"
cat > "$SHIM" <<SHIM_EOF
#!/usr/bin/env bash
# claude-account shim, generated by install.sh. Resolves the plugin's current install
# path on every call so a plugin update never leaves a dangling link.
root=""
reg="\${CLAUDE_CONFIG_DIR:-\$HOME/.claude}/plugins/installed_plugins.json"
if [ -f "\$reg" ] && command -v jq >/dev/null 2>&1; then
  root=\$(jq -r '.plugins | to_entries[] | select(.key | startswith("claude-account@")) | .value[0].installPath // empty' "\$reg" 2>/dev/null | head -n1)
fi
[ -n "\$root" ] && [ -f "\$root/scripts/claude-account.sh" ] || root="$PLUGIN_ROOT"
[ -f "\$root/scripts/claude-account.sh" ] || { echo "claude-account: tool not found under \$root - reinstall the plugin or rerun install.sh" >&2; exit 1; }
exec bash "\$root/scripts/claude-account.sh" "\$@"
SHIM_EOF
chmod +x "$SHIM"
echo "linked  $SHIM  (resolves the plugin path at run time; fallback $PLUGIN_ROOT)"

# Second shim: the standalone statusline, for members who have none yet.
sed -e 's#/scripts/claude-account.sh#/scripts/statusline.sh#g' -e 's#claude-account: tool not found#claude-account-statusline: script not found#' "$SHIM" > "$SHIM-statusline"
chmod +x "$SHIM-statusline"
echo "linked  $SHIM-statusline"
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) echo "note    $BIN_DIR is not in PATH. Add to $RC:  export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac

if [ -f "$RC" ] && grep -qF "$MARK_BEGIN" "$RC"; then
  tmp=$(mktemp "$RC.XXXXXX")
  awk -v b="$MARK_BEGIN" -v e="$MARK_END" '
    $0==b && !done { printf "%s", buf; buf=$0 "\n"; inb=1; next }
    inb { buf=buf $0 "\n"; if ($0==e) { buf=""; inb=0; done=1 }; next }
    { print }
    END { printf "%s", buf }
  ' "$RC" > "$tmp" && mv "$tmp" "$RC"
  verb="updated"
else
  verb="added  "
fi
cat >> "$RC" <<'RC_EOF'

# >>> claude-account >>>
# claude-as [account] [claude args...]
#   Start claude (optionally after switching to <account>). When the statusline flags the 5h
#   quota (accounts/.hop), the next exit switches to the flagged account and resumes the
#   conversation with --continue and the launch options it was started with. CLAUDE_ACCOUNT_AUTOHOP=1 makes
#   that exit automatic.
# Launch options to carry onto `claude --resume`: everything except what picks the conversation (-c, -r,
# --session-id, --fork-session, --from-pr, --teleport) and the opening prompt, which was already sent.
# Values are consumed the way claude parses them: <x> takes one, [x] one unless it starts with -, <x...> until the next flag.
_claude_as_keep() {
  local a mode="" drop=""
  _claude_as_kept=()
  for a in "$@"; do
    case "$mode" in
      one) mode=""; [ -z "$drop" ] && _claude_as_kept+=("$a"); continue ;;
      opt) mode=""; case "$a" in -*) ;; *) [ -z "$drop" ] && _claude_as_kept+=("$a"); continue ;; esac ;;
      many) case "$a" in -*) mode="" ;; *) _claude_as_kept+=("$a"); continue ;; esac ;;
    esac
    drop=""
    case "$a" in
      -c|--continue|--fork-session) ;;
      --resume=*|--session-id=*|--from-pr=*|--teleport=*) ;;
      -r|--resume|--from-pr|--teleport) drop=1; mode=opt ;;
      --session-id) drop=1; mode=one ;;
      --add-dir|--allowedTools|--allowed-tools|--betas|--disallowedTools|--disallowed-tools|--file|--mcp-config|--tools)
        _claude_as_kept+=("$a"); mode=many ;;
      --agent|--agents|--append-system-prompt|--append-system-prompt-file|--autocompact|--client-data-url|--debug-file|\
      --effort|--environment|--fallback-model|--input-format|--json-schema|--max-budget-usd|--model|-n|--name|\
      --output-format|--permission-mode|--permission-prompts|--permission-prompt-tool|--plugin-dir|--plugin-url|\
      --remote-control-session-name-prefix|--setting-sources|--settings|--system-prompt|--system-prompt-file|\
      --system-prompt-snapshot)
        _claude_as_kept+=("$a"); mode=one ;;
      -d|--debug|--cloud|--prompt-suggestions|--remote-control|-w|--worktree)
        _claude_as_kept+=("$a"); mode=opt ;;
      -*) _claude_as_kept+=("$a") ;;
    esac
  done
}
claude-as() {
  local dir="${CLAUDE_ACCOUNT_DIR:-$HOME/.claude/accounts}" next rc keep
  if [ -n "${1:-}" ] && [ -f "$dir/$1.json" ]; then
    claude-account use "$1" || return $?
    shift
  fi
  case " $* " in
    *" -p "*|*" --print "*) CLAUDE_AS_LOOP=1 command claude "$@"; return $? ;;
  esac
  _claude_as_keep "$@"; keep=("${_claude_as_kept[@]}")
  while :; do
    CLAUDE_AS_LOOP=1 command claude "$@"
    rc=$?
    [ -s "$dir/.hop" ] || return $rc
    next=$(cat "$dir/.hop"); rm -f "$dir/.hop"
    # a failed switch must not end the session: resume on whatever login is live
    if claude-account use "$next"; then
      printf 'claude-as: resuming as %s\n' "$next"
    else
      printf 'claude-as: switch to %s failed - resuming on the current login\n' "$next" >&2
    fi
    set -- "${keep[@]}" --continue
  done
}
if [ -n "${ZSH_VERSION:-}" ]; then
  if (( $+functions[compdef] )); then
    _claude_as_names() { compadd -- ${(f)"$(claude-account names 2>/dev/null)"}; }
    compdef _claude_as_names claude-as
  fi
elif [ -n "${BASH_VERSION:-}" ]; then
  _claude_as_names() { COMPREPLY=($(compgen -W "$(claude-account names 2>/dev/null)" -- "${COMP_WORDS[COMP_CWORD]}")); }
  complete -F _claude_as_names claude-as
fi
# <<< claude-account <<<
RC_EOF
echo "$verb claude-as() + completion in $RC  (run: source $RC)"

echo
"$HERE/claude-account.sh" doctor || true
echo
if command -v jq >/dev/null 2>&1 && jq -e '.statusLine.command' "${CLAUDE_CONFIG_DIR:-$HOME/.claude}/settings.json" >/dev/null 2>&1; then
  echo "statusline: you already have one. Source $HERE/statusline-snippet.sh from it so the 5h hop is armed (README > Statusline)."
else
  echo "statusline: none configured. Add to ${CLAUDE_CONFIG_DIR:-$HOME/.claude}/settings.json:"
  echo '            "statusLine": { "type": "command", "command": "bash ~/.local/bin/claude-account-statusline" }'
fi
echo
echo "next:   claude-account save <name>     # snapshot the account you are logged in as now"
