#!/usr/bin/env bash
# Puts the claude-account CLI on PATH and adds the claude-as shell helper + completion.
# Works from a Claude Code plugin install (path resolved live from the plugin registry
# on every call) or from a plain clone (falls back to this checkout).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$HERE/.." && pwd)"
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
SHIM="$BIN_DIR/claude-account"
MARK_BEGIN="# >>> claude-account >>>"
MARK_END="# <<< claude-account <<<"

if [ -z "${RC:-}" ]; then
  case "${SHELL:-}" in
    */bash) RC="$HOME/.bashrc" ;;
    *)      RC="$HOME/.zshrc" ;;
  esac
fi

for dep in jq claude; do
  command -v "$dep" >/dev/null 2>&1 || { echo "install.sh: missing dependency: $dep" >&2; exit 1; }
done
if [ "$(uname -s)" = Darwin ]; then
  command -v security >/dev/null 2>&1 || { echo "install.sh: missing dependency: security (macOS Keychain CLI)" >&2; exit 1; }
fi

chmod +x "$HERE/claude-account.sh"
mkdir -p "$BIN_DIR"
rm -f "$SHIM"
cat > "$SHIM" <<SHIM_EOF
#!/usr/bin/env bash
# claude-account shim, generated by install.sh. Resolves the plugin's current install
# path on every call so a plugin update never leaves a dangling link.
root=""
reg="\${CLAUDE_CONFIG_DIR:-\$HOME/.claude}/plugins/installed_plugins.json"
if [ -f "\$reg" ] && command -v jq >/dev/null 2>&1; then
  root=\$(jq -r '.plugins | to_entries[] | select(.key | startswith("claude-account@")) | .value[0].installPath // empty' "\$reg" 2>/dev/null | head -n1)
fi
[ -n "\$root" ] && [ -f "\$root/scripts/claude-account.sh" ] || root="$PLUGIN_ROOT"
[ -f "\$root/scripts/claude-account.sh" ] || { echo "claude-account: tool not found under \$root - reinstall the plugin or rerun install.sh" >&2; exit 1; }
exec bash "\$root/scripts/claude-account.sh" "\$@"
SHIM_EOF
chmod +x "$SHIM"
echo "linked  $SHIM  (resolves the plugin path at run time; fallback $PLUGIN_ROOT)"
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) echo "note    $BIN_DIR is not in PATH. Add to $RC:  export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac

if [ -f "$RC" ] && grep -qF "$MARK_BEGIN" "$RC"; then
  tmp=$(mktemp "$RC.XXXXXX")
  awk -v b="$MARK_BEGIN" -v e="$MARK_END" '$0==b{skip=1} !skip{print} $0==e{skip=0}' "$RC" > "$tmp" && mv "$tmp" "$RC"
  verb="updated"
else
  verb="added  "
fi
cat >> "$RC" <<'RC_EOF'

# >>> claude-account >>>
# claude-as [account] [claude args...]
#   Start claude (optionally after switching to <account>). When the statusline flags the 5h
#   quota (accounts/.hop), the next exit switches to the flagged account and resumes the
#   conversation with --continue. CLAUDE_ACCOUNT_AUTOHOP=1 makes that exit automatic.
claude-as() {
  local dir="${CLAUDE_ACCOUNT_DIR:-$HOME/.claude/accounts}" next rc
  if [ -n "${1:-}" ] && [ -f "$dir/$1.json" ]; then
    claude-account use "$1" || return $?
    shift
  fi
  case " $* " in
    *" -p "*|*" --print "*) CLAUDE_AS_LOOP=1 command claude "$@"; return $? ;;
  esac
  while :; do
    CLAUDE_AS_LOOP=1 command claude "$@"
    rc=$?
    [ -s "$dir/.hop" ] || return $rc
    next=$(cat "$dir/.hop"); rm -f "$dir/.hop"
    claude-account use "$next" || return $?
    printf 'claude-as: resuming as %s\n' "$next"
    set -- --continue
  done
}
if [ -n "${ZSH_VERSION:-}" ]; then
  if (( $+functions[compdef] )); then
    _claude_as_names() { compadd -- ${(f)"$(claude-account names 2>/dev/null)"}; }
    compdef _claude_as_names claude-as
  fi
elif [ -n "${BASH_VERSION:-}" ]; then
  _claude_as_names() { COMPREPLY=($(compgen -W "$(claude-account names 2>/dev/null)" -- "${COMP_WORDS[COMP_CWORD]}")); }
  complete -F _claude_as_names claude-as
fi
# <<< claude-account <<<
RC_EOF
echo "$verb claude-as() + completion in $RC  (run: source $RC)"

echo
"$HERE/claude-account.sh" doctor || true
echo
echo "next:   claude-account save <name>     # snapshot the account you are logged in as now"
